name: Multi-Job Workflow

on:
  push:
    branches:
      - main

jobs:
  - name: Check Changes
    id: check_changes
    runs-on: self-hosted
    outputs:
      job1_completed: ${{ steps.job1_completed.outputs.job1_completed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Changes
        id: job1_completed
        run: |
          # Add your logic here to check for changes in the repository
          # If changes are detected, set the job1_completed output to true
          echo "::set-output name=job1_completed::true"
          echo "test1"

  - name: Run Katalon Studio
    id: run_katalon
    needs: check_changes
    runs-on: self-hosted
    if: ${{ needs.check_changes.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Katalon Studio
        run: |
          "/Applications/Katalon Studio Engine.app/Contents/MacOS/katalonc" \
          -projectPath="/Users/tatiana.gavrila/git/taco-android-katalon-25oct/taco-android-katalon.prj" \
          -retry=0 \
          -testSuitePath="Test Suites/Sanity EU Android" \
          -browserType="Remote" \
          -executionProfile="Staging" \
          -apiKey="${{ secrets.API_KEY }}" \
          -orgID=230612 \
          -testOpsProjectId=875662 \
          --config \
          -proxy.auth.option=NO_PROXY \
          -proxy.system.option=NO_PROXY \
          -proxy.system.applyToDesiredCapabilities=true \
          -webui.autoUpdateDrivers=true
        shell: bash
