name: Smoke

# on:
#   push:
#     branches: [ main ]
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repository'
        required: true
        
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Set Working Directory
    #   run: cd /Applications/Katalon\ Studio\ Engine.app/Contents/MacOS/
    #   shell: bash
    - name: Run Katalon Studio
      run: |
        "/Applications/Katalon Studio Engine.app/Contents/MacOS/katalonc" -projectPath="/Users/Taco/git/taco-android-katalon-2024/taco-android-katalon.prj" -retry=0 -testSuitePath="Test Suites/Sanity EU Android" -browserType="Remote" -executionProfile="Staging" -apiKey="${{ secrets.API_KEY }}" -orgID=230612 -testOpsProjectId=875662 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true
      shell: bash
